### ISSUE TITLE
shittyserver is being shitty (and crashing)

### ISSUE THREAD

**Issue by ashhhleyyy** [UniversityRadioYork/WebStudio#303]
```
Oct 29 22:43:18 dolby python3[569281]: Exception in callback AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...te 'planes'")>) at /usr/local/lib/python3.9/dist-packages/pyee/asyncio.py:65
Oct 29 22:43:18 dolby python3[569281]: handle: <Handle AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...te 'planes'")>) at /usr/local/lib/python3.9/dist-packages/pyee/asyncio.py:65>
Oct 29 22:43:18 dolby python3[569281]: Traceback (most recent call last):
Oct 29 22:43:18 dolby python3[569281]:   File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
Oct 29 22:43:18 dolby python3[569281]:     self._context.run(self._callback, *self._args)
Oct 29 22:43:18 dolby python3[569281]:   File "/usr/local/lib/python3.9/dist-packages/pyee/asyncio.py", line 71, in callback
Oct 29 22:43:18 dolby python3[569281]:     self.emit("error", exc)
Oct 29 22:43:18 dolby python3[569281]:   File "/usr/local/lib/python3.9/dist-packages/pyee/base.py", line 179, in emit
Oct 29 22:43:18 dolby python3[569281]:     self._emit_handle_potential_error(event, args[0] if args else None)
Oct 29 22:43:18 dolby python3[569281]:   File "/usr/local/lib/python3.9/dist-packages/pyee/base.py", line 139, in _emit_handle_potential_error
Oct 29 22:43:18 dolby python3[569281]:     raise error
Oct 29 22:43:18 dolby python3[569281]:   File "/opt/webstudioserver/shittyserver.py", line 290, in on_track
Oct 29 22:43:18 dolby python3[569281]:     transfer_buffer1.write(new_frame.planes[0])
Oct 29 22:43:18 dolby python3[569281]: AttributeError: 'list' object has no attribute 'planes'
```

**Comment by markspolakovs** [comment]
looks like a ffmpeg binding breaking change :(
